services:
  composernormalize:
    version:        latest

  phpcs:
    version:        latest
    config_path:      ~
    paths:        ['src']

  phpcsfixer:
    version:        latest
    config_path:      .php_cs.dist
